{% set name = "eldorado" %}
{% set version = "0.1.0" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  git_rev: "v{{ version }}"
  git_url: git@github.com:MOMA-AUH/eldorado.git

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  number: "{{ build_number }}"

requirements:
  build:
    - python
    - setuptools
    - pytest
    - pip
    - git
  run:
    - python>=3.10
    - samtools>=1.17
    - typer>=0.9.0
    - pytest>=8.1.1
    - pod5>=0.3.10